name: Build App

on:
  push:
    branches:
      - master

concurrency: ci-${{ github.ref }}

jobs:
  
  build-cl-app:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC-2022",
            os: windows-latest,
            artifact: "windows_msvc2022.7z",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 17 2022"
          }


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/source-code
          submodules: true # Recursively checkout submodules

      - name: Setup Dev Env 
        uses: ./source-code/.github/actions/setup_dev_env

      - name: Configure and build
        shell: pwsh
        working-directory: ${{runner.temp}}
        run: |
          if (-Not (Test-Path 'build_${{ runner.os }}_cl')){ mkdir build_${{ runner.os }}_cl }
          cd build_${{ runner.os }}_cl
          $prefix = "${{runner.temp}}/install"
          $install_dir = "cambio_cl_latest"
          cmake -S "${{ github.workspace }}/source-code" -B "${{runner.temp}}/build_${{ runner.os }}_cl" -DBUILD_CAMBIO_GUI=OFF -DBUILD_CAMBIO_COMMAND_LINE=ON -DSpecUtils_INJA_TEMPLATES=ON -DSpecUtils_ENABLE_URI_SPECTRA=ON -DSpecUtils_ENABLE_D3_CHART=ON -DSpecUtils_D3_SUPPORT_FILE_STATIC=ON -DSpecUtils_FLT_PARSE_METHOD=FromChars -DSpecUtils_SHARED_LIB=OFF -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_PREFIX_PATH="${{runner.temp}}\install" -DBoost_USE_STATIC_RUNTIME=ON -DNO_CMAKE_SYSTEM_PATH=ON -DCMAKE_FIND_USE_CMAKE_SYSTEM_PATH=OFF -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_CONFIGURATION_TYPES="Release"
          cmake --build "${{runner.temp}}/build_${{ runner.os }}_cl" --config Release
          ls
          ls "${{runner.temp}}/build_${{ runner.os }}_cl"
          ls "${{runner.temp}}/build_${{ runner.os }}_cl/Release"
          Get-ChildItem cambio_cl_${{ runner.os }}*.zip | foreach { Remove-Item -Path $_.FullName }
          echo "After removing old zip files"
          ls
          if (Test-Path -Path "cambio_cl_${{ runner.os }}" ){ Remove-Item -Path "cambio_cl_${{ runner.os }}" -Recurse -Force }
          mkdir "cambio_cl_${{ runner.os }}"
          cp "${{runner.temp}}/build_${{ runner.os }}_cl/Release/*.exe" "${{runner.temp}}/build_${{ runner.os }}_cl/cambio_cl_${{ runner.os }}/"
          $notes = "cambio_cl_${{ runner.os }}\build_info.txt"
          echo "This is an automated build of cambio_cl for ${{ runner.os }} built on the github infrastruction at $(date)" >> $notes
          echo "No testing has been performed on this build." >> $notes
          echo "cambio code git has SHA ${{ github.sha }}" >> $notes
          echo "Contact cambio@sandia.gov for support." >> $notes
          echo "Before zipping, files present for the bbuild are:"
          ls
          ls .\cambio_cl_${{ runner.os }}
          Compress-Archive -CompressionLevel Optimal -Path .\cambio_cl_${{ runner.os }} -DestinationPath cambio_cl_${{ runner.os }}_${{ runner.os }}_$(get-date -f yyyy-MM-dd).zip 
          echo "After zipping, files present for the build are:"
          ls

      # Update the bleeding-edge tag to be current commit
      - name: Run latest-tag
        uses: EndBug/latest-tag@v1.6.1
        with:
          ref: bleeding-edge
          description: Latest successful automated CL build

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: '${{runner.temp}}\build_${{ runner.os }}_cl\cambio_cl_${{ runner.os }}*.zip'
          draft: false
          prerelease: true
          body: "An automated, and untested build of the "command line" version of cambio, with the latest code pushed to the repository, for Windows."
          allowUpdates: true
          generateReleaseNotes: false
          name: "Development Build"
          removeArtifacts: true
          replacesArtifacts: true
          tag: 'bleeding-edge'
          commit: ${{ github.sha }}
          makeLatest: true


      - name: "Cleanup and finish"
        run: |
          Get-ChildItem cambio_cl_${{ runner.os }}*.zip | foreach { Remove-Item -Path $_.FullName }
          echo "Job status is ${{ job.status }}."